[build]
  publish = "public"
  command = "echo 'Static site: no build step required'"

[[redirects]]
  from = "/bot-invite"
  to = "https://discord.com/oauth2/authorize?client_id=963487472300482560"
  status = 302

[[redirects]]
  from = "/support-invite"
  to = "https://discord.gg/bJ8dqwSCuU"
  status = 302
